services:
  postgres:
    container_name: new-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "TaskManager"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
volumes:
  postgres-data:
